### ISSUE TITLE
'undefined exports: Metadata' when trying to install package

### ISSUE THREAD

**Issue by ekrimmel** [hrhwilliams/ArctosR#1]
Hi Harlan, I am trying to install and test this package but getting the following error in RStudio:

![Screen Shot 2024-08-23 at 10 57 22](https://github.com/user-attachments/assets/79e3a98d-d754-407b-babc-97659186b682)

And this is my local context:

![Screen Shot 2024-08-23 at 11 03 33](https://github.com/user-attachments/assets/cf406cf4-9d47-4b2a-b241-ff15e7ade972)

Any thoughts?

**Comment by hrhwilliams** [comment]
Hi, thanks for reporting this. It looks like the documentation for a class I was working on snuck in to one of my commits. My latest commit removed that so if you attempt to download the latest version of the repository it should work for you now.

**Comment by ekrimmel** [comment]
Yep, works like a charm now! Thank you :)
