### ISSUE TITLE
Get_records doesn’t honor limit past the initial request.

### ISSUE THREAD

**Issue by oakmanjacob** [hrhwilliams/ArctosR#4]
# Issue
When using get_records with all_records = TRUE and limit = 1000, the initial request will pull 1000 records but the rest of the records seem to be pulled 100 at a time.

This goes against the documentation of the limit parameter “limit (numeric) The maximum number of records to download at once. Default is 100”

## Why this matters
Each API call increases the time get_records takes to complete which can be very long for large datasets. Allowing the user to control the batch size will improve this time and reflect the documentation of the limit parameter.

## Solution
Update `frontend.R` to use the same limit as the first query instead of hard coding it to 100 in the get_records function.

**Comment by hrhwilliams** [comment]
Thanks for pointing this out. I implemented your suggestion, so now limit will be used for every request when specifying all_records, and not just the initial request.
